config/routes.rb
ElDream::Application.routes.draw do

  devise_for :users

  resources :ideas

  resources :lists

  root :to => "dream_core#home"

  match "/lists", to: "dream_core#lists"

  match "/about", to: "dream_core#about"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :idea, :list_id
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  has_many :ideas
  belongs_to :user
 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :lists 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dream_core_controller.rb
class DreamCoreController < ApplicationController
  before_filter :authenticated
  def home
  	@selected_tab = 'home'
  end

  def lists
  end

  def about
  end

  private

  def authenticated
      redirect_to(:lists) if user_signed_in?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new(list_id: params[:list_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_filter :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where(:user_id => current_user.id)
    @idea = Idea.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dream_core_helper.rb
module DreamCoreHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/dream_core/about.html.erb
<h1>DreamCore#about</h1>
<p>Find me in app/views/dream_core/about.html.erb</p>

app/views/dream_core/home.html.erb
<div class="container">

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Get your idea machine going.</h1>
        <p class="lead">Make a list with 10 ideas about any topic every day.</p>
        <a class="btn btn-large btn-success" href="users/sign_up">Get started today</a>
      </div>

app/views/dream_core/lists.html.erb
<h1>DreamCore#lists</h1>
<p>Find me in app/views/dream_core/lists.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :list_id %>

  <div class="field">
    <%= f.label :idea %><br />
    <%= f.text_area :idea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>List</th>
    <th>Idea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.list_id %></td>
    <td><%= idea.idea %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @idea.list_id %>
</p>

<p>
  <b>Idea:</b>
  <%= @idea.idea %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', list_path(@idea.list_id) %>

app/views/layouts/_footer.html.erb
<footer>
  &copy; <%= Time.now.year %> El Dream	
</footer>

app/views/layouts/_header.html.erb
<h1>El Dream</h1>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>  
      <a class="brand" href="/">El Dream</a>
      <div class="nav-collapse">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %>
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %> 
          <% end %>
        </p>    
        <ul class="nav">
          <li class="<%= 'active' if @selected_tab == 'home' %>"><%=link_to "Home", root_path %></li>
          <li><%=link_to "Lists", lists_path %></li>
          <li><%=link_to "About", about_path %></li>
        </ul>
      </div> 
    </div>     
  </div>  
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElDream</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>

  <div class="container">

<% if !notice.nil? %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if !alert.nil? %>
  <p class="alert"><%= alert %></p>
<% end %>

<%= render "layouts/navigation" %>

<%= yield %>

<%= render "layouts/footer" %>

  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><a class="show-ideas" href="#" data-toggle="modal" data-target="#modal-<%=list.id %>"><%= list.name %></a></td>
    <td><%= list.created_at.strftime("%B %d, %Y") %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <div id="modal-<%= list.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= list.name %></h3>
  </div>
  <div class="modal-body">
    <%= form_for @idea, remote: true do |f| %>
    <%= f.text_field :idea %>
    <%= f.submit %>
    <%= hidden_field_tag 'ideas_list_id', list.id %>
<% end %>   
    <p>
    <% list.ideas.each_with_index.map do |idea, index| %>
   <p>
    <%= index += 1 %>. <%= idea.idea %>
  </p>
    <% end %>
</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>
<% end %>
</table>

<br />
 

<%= link_to 'New List', new_list_path %>

  <script> 
//   $('.show-ideas').click(function (e) { 
//     e.preventDefault() ;
//     $('#myModal').modal('show') ;
//     $("#idea_list_id").val($(this).attr('data'));
//   });
  </script>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @list.name %>
</p>
<p>
  <% @list.ideas.each_with_index.map do |idea, index| %>
  <p>
    <td><%= index += 1 %>. <%= idea.idea %></td>
  </p>
    <% end %>  
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'New Idea', new_idea_path(list_id: @list) %> |
<% end %>
<%= link_to 'Back', lists_path %>